[project]
name = "linuxtips-python-webapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gunicorn>=23.0.0",
    "legacy-cgi>=2.6.3",
]
